### ISSUE TITLE
Doesn't work in FragmentPagerAdapter

### ISSUE THREAD

**Issue by pommedeterresautee** [DHuckaby/Prime#11]
I used your lib in my own opensource project.

I have a Fragment, which contains a FragmentPagerAdapter... which display another fragment.
Inside the last fragment I just have a RemoteImageView.

When I launch the fragment, the first time the lib download and display the image.

But when I call it a second time... it doesn't work, nothing appears. Do you have an idea?

I there a way to revoke the cache ?

I have tried also with synchronous option, doesn t work neither!

Link:  https://github.com/pommedeterresautee/2borange/blob/Development/2BOrange/src/com/pommedeterresautee/twoborange2/Fragment/ScreenShotViewer/ScreenshotContentFragment.java

**Comment by DHuckaby** [comment]
In my implementations it works perfectly, this doesn't sound like a problem with the library.

**Comment by pommedeterresautee** [comment]
You are right, in your example app it works. You put the view pager in its own activity, so when you push precedent you kill the activity. When I put the view pager in its own activity in my app, it works too for the same reason. It doesn't work when you put the view pager in a fragment, push precedent, so the fragment is just removed of the stack but the activity is not killed and you come back in the fragment, the image, this time, is not displayed.

**Comment by DHuckaby** [comment]
Putting a ViewPager inflated with Fragments within a Fragment breaks the lifecycle pattern, doing so will result in the lifecycles of the inner Fragments to not work correctly resulting in the correct calls not being made to display the image.
