### ISSUE TITLE
Ability to set bitmapFactoryOptions.inPreferredConfig in ImageManager/decodeFromByteArray or decodeFrom*

### ISSUE THREAD

**Issue by sidcpatel** [DHuckaby/Prime#12]
Thanks for providing this library.

It will be useful if we can control the preferredConfig setting. This will allow us to reduce the memory footprint in low memory devices.  

bitmapFactoryOptions.inPreferredConfig = (lowMemoryDevice ? Config.RGB_565 : Config.ARGB_8888);

This can be a per image setting or Image Manager setting.

**Comment by DHuckaby** [comment]
I can either add it to ExtendedRequest and you will have to roll your own RemoteImageView to use it or I can add it to the Configuration but that isn't accessible at runtime, only compile time. Which do you prefer?

**Comment by sidcpatel** [comment]
It will be important to set the image quality at runtime so that it can be set based on available memory (max app vm heap). Devices with more memory can have better quality images.

Compile time setting will not work.

As long as we can extend the RemoteImageView and set "bitmapFactoryOptions.inPreferredConfig" for the image that will be loaded in it, it will work.

**Comment by sidcpatel** [comment]
Thanks for making this change. I will pick it up in your next version of jar.

**Comment by DHuckaby** [comment]
I won't be pushing out a new version soon, use master if you need the changes immediately.
