### ISSUE TITLE
Ability to dynamically specify Configuation parameters

### ISSUE THREAD

**Issue by sidcpatel** [DHuckaby/Prime#14]
We would want to specify different configuration values for phones vs tablets (based on screen size or screen density).

MEM_CACHE_SIZE_KB
DISK_CACHE_SIZE_KB
ASYNC_THREAD_COUNT
## DOWNLOAD_LOCATION

If there are other users/developers who would want this, then it will be nice to have feature.

**Comment by DHuckaby** [comment]
The issue with adding the ability to modify the global configuration options is we only initialize once, with all of the configuration options taken into account. Once we are initialized we are unable to modify the options.

I understand the need to be able to do that but you shouldn't rely on such things as screen size and density to determine the processing power, network latency, or memory consumption that the configuration parameters address.

With the latest revision I have added dynamic scaling of the memory cache and asynchronous thread count depending on the device running it, that is if you are not already overriding the default value.

If you still request the feature after reading my thoughts on why I shouldn't implement it please recommend a way that I can add it without breaking the current scheme of the library. I have gone down the path of adding this feature in the past and I have never found an implementation that I like that still keeps a global state.

**Comment by DHuckaby** [comment]
Closing this for now, feel free to request it to be re-opened if you feel it is still a valid request.

**Comment by sidcpatel** [comment]
Thanks for the reply.  We can leave the configuration of the global settings as it is.

I was thinking of increasing the memcache (mLruCache) size for Nexus 7 (or devices with larger heap memory). The current dynamic scaling of the memory cache and asynchronous thread count will help. However, if you declare MEM_CACHE_SIZE_KB (and others)  as non-final public static variable, application writer can dynamically choose the sizes based on device capacity and activity requirements.  This is just an option if this comes up again.

While thinking about this, I realized that what I need is direct access to mLruCache  to control cache size.
I need mLruCache that is big enough for the activity A,B,C in my app, so that images are displayed quickly. However, when I start activity D, I want to clear or reduce/trim the size of the mLruCache so that activity D can use more memory. 

LruCache implementation has evictAll method; however, it is not exposed through the ImageManager.  Allowing application to control mLruCache size will be very useful.

**Comment by DHuckaby** [comment]
The LruCache that I use for the Bitmap memory caching does not support dynamic cache size changes, because of this I must know exactly how large I should create it as when the ImageManager is created the first time.

If you are running out of memory cache between activities then you might want to consider displaying less images if its possible. Evicting the in memory Bitmap's will not fix that issue and even if you did the garbage collector is not guaranteed to actually recycle them in time and then you will end up in a memory constrained environment.

The pattern I follow is made to create a global image management system that handles image loading in the most efficient way possible while not sacrificing simplicity at an api level.

**Comment by sidcpatel** [comment]
In my case, I have lots of small images for a store. I use Prime to manage those images. However, user can pick an item in the store and that will lead to a memory intensive activity which does not use Prime (also it cannot use Prime). I would prefer to clean out the memory used by the mLruCache once the 2nd acitivity resumes.

I understand that the garbage collector will not recycle the bitmaps right away. However, if that occurs eventually, I am fine with that because I know I don't need the mLruCache images anymore (at least for a while until the 2nd activity ends). (Can we use bitmap.recycle() while evicting bitmaps from the mLruCache? This will free up the memory right away assuming the images are not currently displayed.)

---

I sent a pull request for the change that I was suggesting. I wanted to try to commit to a github project. Feel free to reject it if you are not convinced or want more changes.

**Comment by DHuckaby** [comment]
From what you are explaining I would suggest a smaller memory cache size, that will reduce the memory footprint Prime has while inside of your memory consuming activity. If you try to call recycle() on a Bitmap and it is still attached to a View if it tries to use that Bitmap again it will throw an Exception.

**Comment by sidcpatel** [comment]
Ok. Thanks.  I will continue with the small cache size.
